export declare const enum Addressing {
    UNKNOWN = 0,
    IMPLIED = 1,
    ACCUMULATOR = 2,
    IMMEDIATE = 3,
    IMMEDIATE16 = 4,
    ZEROPAGE = 5,
    ZEROPAGE_X = 6,
    ZEROPAGE_Y = 7,
    ABSOLUTE = 8,
    ABSOLUTE_X = 9,
    ABSOLUTE_Y = 10,
    INDIRECT = 11,
    INDIRECT_X = 12,
    INDIRECT_Y = 13,
    RELATIVE = 14
}
export declare const enum OpType {
    UNKNOWN = 0,
    NOP = 1,
    LDA = 2,
    STA = 3,
    LDX = 4,
    STX = 5,
    LDY = 6,
    STY = 7,
    TAX = 8,
    TAY = 9,
    TXA = 10,
    TYA = 11,
    TXS = 12,
    TSX = 13,
    ADC = 14,
    SBC = 15,
    INX = 16,
    INY = 17,
    INC = 18,
    DEX = 19,
    DEY = 20,
    DEC = 21,
    AND = 22,
    ORA = 23,
    EOR = 24,
    ROL = 25,
    ROR = 26,
    ASL = 27,
    LSR = 28,
    BIT = 29,
    CMP = 30,
    CPX = 31,
    CPY = 32,
    JMP = 33,
    JSR = 34,
    RTS = 35,
    RTI = 36,
    BCC = 37,
    BCS = 38,
    BPL = 39,
    BMI = 40,
    BNE = 41,
    BEQ = 42,
    BVC = 43,
    BVS = 44,
    PHA = 45,
    PHP = 46,
    PLA = 47,
    PLP = 48,
    CLC = 49,
    SEC = 50,
    SEI = 51,
    CLI = 52,
    CLV = 53,
    SED = 54,
    CLD = 55,
    BRK = 56
}
export interface Instruction {
    opType: OpType;
    addressing: Addressing;
    bytes: number;
    cycle: number;
}
export declare const kIllegalInstruction: Instruction;
export declare const kInstTable: Instruction[];
